### ISSUE TITLE
Discrepancies Between IAB Documentation and IAB GPP Encoder/Decoder Tool or CMP's

### ISSUE THREAD

**Issue by pm-nitin-shirsat** [InteractiveAdvertisingBureau/Global-Privacy-Platform#112]
Hello Team,

I have noticed discrepancies between the IAB documentation [IAB GPP Doc](https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform) and the IAB GPP encoder/decoder tool [IAB Decoder/Encoder Tool](https://iabgpp.com/#DBABMA~CQAdTsAQAdTsAPoABABGA5EAAAAAAAAAAAAAAAAAAAAA.QAAA.IAAA)

The conflicts/issues are as follows: 
1. The value types of parsed sections differ. 
According to the IAB documentation, they should be an **array of objects**, whereas the decoder tool shows them as an **object** (Attached image for shows how decoder tool uses **objects** whereas **array of objects** is mentioned in the documentation under _getSection_ command)
2. The decoding parameters(properties) for TCFEU2 have different **names** in the IAB documentation than the decoder tool (Highlighted in the attached image for reference)
3. In the GPC subsection,
	1. The field names vary: the IAB documentation uses "SubsectionType" while the decoder tool uses "GpcSegmentType". Which one is the right one? 

My questions are: 
	1. Is there a plan to fix these discrepancies? If yes, is there a timeline?
	2. As of today, which format should CMPs follow (referring to conflicts in points 1 and 2)? 

**NOTE**: We observed that most CMPs currently use the format provided by the decoder tool rather than the IAB documentation.

Your insights would be greatly appreciated.

<img width="1703" alt="Discrepancy_IAB_doc_ _tool" src="https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/assets/107102698/991e4976-5447-4a4c-8b07-ca47eb543c6b">

**Comment by lamrowena** [comment]
@pm-nitin-shirsat For all three issues you've highlighted the spec is correct and the tool is incorrect. We will fix these in the tool.

**Comment by pm-nitin-shirsat** [comment]
Thank you @lamrowena !
