### ISSUE TITLE
How to wait for Consent

### ISSUE THREAD

**Issue by sailerinteractive** [InteractiveAdvertisingBureau/Global-Privacy-Platform#124]
How do you wait to execute a piece of code until a user has first interacted with the consent dialog in a multi-jurisdictional setup? My initial idea was to wait until "signalStatus" is "ready". However, with the CMP I am testing, it seems like the status is set to ready before the user has even interacted with the consent prompt. Is this a bug in the implementation? Or is there another way to determine if a user has completed the consent dialog? 

Thanks!

**Comment by HeinzBaumann** [comment]
You should use the addEventListener and check/wait for the status for consent complete or soemthing like that. check the API documentation for the correct trigger to watch for.

**Comment by sailerinteractive** [comment]
I assume you mean signalStatus=="ready" ?

**Comment by HeinzBaumann** [comment]
I believe that it is the singalStatus=="ready". I would also check the sectionChange.

**Comment by patmmccann** [comment]
> However, with the CMP I am testing, it seems like the status is set to ready before the user has even interacted with the consent prompt. Is this a bug in the implementation?

It should be configurable in your CMP. In many opt-out jurisdictions, the signal is ready immediately. Publishers can choose to say it isn't ready via their CMP configuration if they want to wait for modal interaction or timeout.

**Comment by patmmccann** [comment]
Feel free to check out our implementation at prebid of checking for ready and listening for changes https://github.com/prebid/Prebid.js/blob/acdeb2770c825b0f489e19424e558d2710172d78/modules/consentManagementGpp.js#L89
