### ISSUE TITLE
Several issues in TCF EU Section spec

### ISSUE THREAD

**Issue by HeinzBaumann** [InteractiveAdvertisingBureau/Global-Privacy-Platform#126]
There are several issues in the TCF EU Section spec. (See diffs below.) 

[CMP API Specification.txt](https://github.com/user-attachments/files/17213003/CMP.API.Specification.txt)
[GPPExtension: IAB Europe TCF.txt](https://github.com/user-attachments/files/17212997/GPPExtension.IAB.Europe.TCF.txt)

PR is progress.

**Comment by lamrowena** [comment]
Fixed in https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/pull/127
