### ISSUE TITLE
Deletion API appears to be missing

### ISSUE THREAD

**Issue by AramZS** [InteractiveAdvertisingBureau/Global-Privacy-Platform#17]
Both the LSPA and the USP API specifies an API for passing deletion requests to other systems. 

This mechanism is expected as part of compliance with California law. 

I do not see the deletion API specified in this spec. Is it here and I'm missing it? Is there a plan to have it in place by Jan 1? It would be impossible to move off of USP API without this mechanism. 

If it is not here, I propose we move the deletion API as it exists inside USP API, as is, whole into GPP. Preferably not under an API Prefix, since it applies in multiple regional regimes.

**Comment by lamrowena** [comment]
An updated deletion specification has been released and is available here: https://github.com/InteractiveAdvertisingBureau/Data-Subject-Rights/blob/main/Data%20Deletion%20Request%20Framework.md
