### ISSUE TITLE
Definition of N-Bitfield is missing

### ISSUE THREAD

**Issue by janwinkler** [InteractiveAdvertisingBureau/Global-Privacy-Platform#19]
Definition of N-Bitfield is missing but used in US National

**Comment by bgazzera** [comment]
@janwinkler I may be way wrong, but my assumption is that a N-Bitfield(x,y) is made up of y elements of type Integer (fixed length of x)

For example a N-Bitfield(2,3) would be 3 integers (fixed length of 2) concatenated together.
if a integer(2) looks like "00", an N-Bitfield(2,3) would look like "000000". In this case each element of the bitfield could hold a value 0-3. 

In the [uspca section](https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/main/Sections/US-States/CA/GPP%20Extension:%20IAB%20Privacy%E2%80%99s%20California%20Privacy%20Technical%20Specification.md) you can see that the `SensitiveDataProcessing` field is defined as a N-Bitfield(2,9) where each of the 9 consents that are encoded can be of value 0-2, which fits in a int(2).

**Comment by janwinkler** [comment]
yes the understanding is correct. but it needs to be explicitly stated in the gpp spec. just for completeness :-)

**Comment by janwinkler** [comment]
@lamrowena it also needs to be added as a new line here:
https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/main/Core/CMP%20API%20Specification.md#in-app-key-names

E.g.
Input Data Type: N-Bitfield
In-app Data Type: String
Description: Convert into array by treating each key:value pair as index and value. Create an array with [0 .. max(index)] items where each item contains the value. Use empty string for non-existing items. Then convert the array into a string separated by underscore. Given {1:0, 5:2, 8:1} the converted array is ['','0','','','','2','','','1'] and the resulting string is "_0____2___1"

**Comment by lamrowena** [comment]
Addressed in https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/pull/83/
