### ISSUE TITLE
ApplicableSection length issue; Sectionlist unclear

### ISSUE THREAD

**Issue by patmmccann** [InteractiveAdvertisingBureau/Global-Privacy-Platform#21]
Current spec says

https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/58220e6e76b0f6e3006f1712b52cbed501792c3f/Core/CMP%20API%20Specification.md?plain=1#L569

The characterization of multiple sections as rare seems strange, as well as the max length of two.

Here is simple scenario where there are four applicable sections:

A Utah resident on an EU based website that has determined GDPR always applies, Utah law applies, who is travelling in California, and the publisher wants to emit both usp and usn strings for backwards compatibility. 

Also, the spec makes it difficult to determine the difference between sectionList and applicableSections

**Comment by janwinkler** [comment]
FYI: The field is currently under discussion and is likely to be changed.
