### ISSUE TITLE
Does IAB intend to provide an official GPP string processor implementation in Java, as was done for TCF v1/2?

### ISSUE THREAD

**Issue by CoreyZelkowitz** [InteractiveAdvertisingBureau/Global-Privacy-Platform#26]
Does IAB intend to provide an official GPP string processor implementation in Java, as was done for TCF v1/2? I do not see any mention of this. The CA/VA privacy laws going into effect just over 1 month from now (assuming no delays and publisher/cmp participation).

**Comment by janwinkler** [comment]
see https://github.com/IABTechLab/iabgpp-java

**Comment by ym-corey** [comment]
There doesn't seem to be any release version for this library, nor any entry on the maven central link in the README.

**Comment by lamrowena** [comment]
@ym-corey the library posted isn't ready yet but the plan is to finalize that soon

**Comment by lamrowena** [comment]
Library has been published so closing this issue
