### ISSUE TITLE
TCF EU extension update

### ISSUE THREAD

**Issue by janwinkler** [InteractiveAdvertisingBureau/Global-Privacy-Platform#36]
The Publisher restrictions field is not really compatible with GPP since it does not reflect one (1) datatype but mutlitple in an unknown amount. The correct datatype would be:

Name: "RestrictionDataType" (or whatever)
Encoding: variable
JS API output: Object of Name-Number pairs (e.g. {1: {13:2, 15:1, 17:0, 18:0}, 2:{11:2, 12:1, 13:0, 15:0}}

"RestrictionDataType" : consists of
 - "num" as Int(12)
 - Per Amount of "num":
 - - "purposeID" int(6)
 - - "value" int(2)
 - - "ids" Range (int)

Where "num" defines the amount of restrictions to come. for each restriction there is a prupose ID and a restriction type followed by a range of IDs for which these restrictsion are valid.

**Comment by HeinzBaumann** [comment]
@janwinkler this is quite old. Is this still wrong in the latest EEA/UK Section spec? 
This is what I currently have:
 <tr style="background-color:#000;color:#FFF;">
    <td>
      <strong>Publisher Restrictions Section</strong>
    </td>
    <td colspan=2>The content of this section is optional EXCEPT for NumPubRestrictions. Encodes any number of single or range restriction entries.
    </td>
  </tr>
  <tr>
  <td>NumPubRestrictions</td>
  <td>Int(12)</td>
  <td>Number of restriction records to follow.<br>Value is required even if it is <code>0</code></td>
  </tr>
  <tr>
  <td>PurposeID</td>
  <td>Int(6)</td>
  <td>The Vendor’s declared Purpose ID that the publisher has indicated that they are overriding.</td>
  </tr>
  <tr>
  <td>RestrictionType</td>
  <td>Int</td>
  <td><code>0</code> Purpose Flatly Not Allowed by Publisher (regardless of Vendor declarations)<br><code>1</code> Require Consent (if Vendor has declared the Purpose IDs legal basis as Legitimate Interest and flexible)<br><code>2</code> Require Legitimate Interest (if Vendor has declared the Purpose IDs legal basis as Consent and flexible)<br><code>3</code> UNDEFINED (not used)</td>
  </tr>
  <tr>
  <td>PubRestrictionEntry*</td>
  <td>OptimizedIntRange</td>
  <td>A single or range of Vendor ID(s) who the publisher has designated as restricted under the Purpose ID in this PubRestrictionsEntry<br><br>Equivalent of the fields listed under the Publisher Restrictions Section as defined in the <a href="https://github.com/InteractiveAdvertisingBureau/GDPR-Transparency-and-Consent-Framework/blob/master/TCFv2/IAB%20Tech%20Lab%20-%20Consent%20string%20and%20vendor%20list%20formats%20v2.md">TCF v2 specification:</a><br>MaxVendorId, <br>IsRangeEncoding,<br>BitField, NumEntries, IsARange, StartOrOnlyVendorId, EndVendorId</td>

**Comment by janwinkler** [comment]
The encoding would work but the JS API wouldnt know what to output. Thats why with the last iteration of the core spec we added ArrayOfRanges and N-ArrayOfRanges. ArrayOfRanges would be the correct datatype for the Restriction replacing all fields from NumPubRestrictions up to the end with one field (call it PubRestrictions or something)

**Comment by janwinkler** [comment]
ps: see tcf canada, there we already went one step further and used N-ArrayOfRanges instead of ArrayOfRanges

**Comment by lamrowena** [comment]
Fixed in https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/pull/127
