### ISSUE TITLE
Clarification on event status

### ISSUE THREAD

**Issue by janwinkler** [InteractiveAdvertisingBureau/Global-Privacy-Platform#37]
Under TCF EU the event status tcloaded / useractioncomplete were used to determine when the end of the user activity is reached. With the current GPP events, there seems to be no similar thing. Can one assume that the following is correct?

TCF "tcloaded" equals to GPP's:
cmpStatus = "loaded" + cmpDisplayStatus = "disabled"

TCF "cmpuishown" equals to GPP's:
cmpStatus = "loaded" + cmpDisplayStatus = "visible"

TCF "useractioncomplete" equals to GPP's:
cmpStatus = "loaded" + cmpDisplayStatus = "hidden"

Especially the last case seems not to be 100% accurate since there are case when the CMP is loaded but the interface is not **yet** loaded (but will load in a few moments). 

In order to make it more clear, I'd propose to update the Ping Status Codes and separate the codes of cmpDIsplayStatus into:

- visible - Interface is currently shown (vendor shall wait for next events)
- hidden - Interface is not yet displayed, CMP has not yet decided to show the interface (vendors shall wait for next event)
- disabled - Interface was shown and is now closed or will not show (no sections apply or data is already current and does not need a renewal, vendors can query the gpp data)

**Comment by patmmccann** [comment]
At prebid we're struggling with this as well; we're assuming, as many of our published are implementing this way, that cmp status will always be visible in the United States. Since useractioncomplete doesn't really have an equivalent; we're simply using status loaded and proceeding with an auction.

**Comment by janwinkler** [comment]
@patmmccann 
Thats interesting, so you would say that the "Do not sell my ...."-Link on the page is equivalent to the CMP being visible. How would a publisher than be able to tell the vendor that the website does not incliude the link (but instead the notification layer is open/visible)? Or in case when there is a link and a notice/banner - wouldnt a vendor want to wait until the user decided (closed that banner) before starting with advertising? (e.g. the visitor could use the banner to opt-out ...)

Does it mean we need a forth and/or independent status? Something like cmpOutOutLinkStatus = "unknown/notApplicable/visible/notVisible"?

**Comment by patmmccann** [comment]
> so you would say that the "Do not sell my ...."-Link on the page is equivalent to the CMP being visible.

exactly

> How would a publisher than be able to tell the vendor that the website does not incliude the link (but instead the notification layer is open/visible)? 
there is no way :(

I'm not sure at all the best way forward, I look forward to the discussion

**Comment by dgirardi** [comment]
I think it'd be wise to separate the idea of "cmp is visible" from "user is being prompted" - or be explicit that "visible" means the latter, as the implementation examples seem to suggest.

**Comment by patmmccann** [comment]
cmpDisplayStatus = 'onpage' could be a new display status?

**Comment by janwinkler** [comment]
"onpage" woulnt be sufficient or? e.g. if you have both (opt out link and notice layer), would it then be cmpDisplayStatus = "onpage+visible" or would there be two events right after each other?

**Comment by dgirardi** [comment]
My preference, as a Prebid developer, would be a separate flag that indicates whether the user needs to take action (which was the `useractioncomplete` event in TCF). Maybe `pingStatus.userActionComplete = true/false`. It's possible that this is what 'visible' is supposed to mean, if so, it should be stated explicitly IMO.

I am not interested at all in the visibility of the CMP - all I need to know is, is the user likely to change consent in the next few seconds?

**Comment by patmmccann** [comment]
>. if you have both (opt out link and notice layer)

I am having trouble finding the code section, but I thought this was illegal, that opt out and notice most be adjacent and in the same layer.

**Comment by janwinkler** [comment]
@patmmccann What do you mean with "illegal"? unwanted by the gpp spec or unwanted by CCPA/PEPIDA/GDPR/whatever?

**Comment by patmmccann** [comment]
unwanted by California law

**Comment by janwinkler** [comment]
just re-read your comment. i think we mean two different thinks: with "opt out link" i meant the "do not sell my personal data" link (the link that opens/shows the opt-out page), not the link that performs the actual opt out.

basically the question is whether we want to separate between the four states:

a) the "potential" to see the notice (by having the do-not-sell-link on the page, some websites seem to see this as sufficient and do not show any overlay/notice unless you click that link)
b) actually showing the notice (e.g. layer opens or user navigates to opt-out-page) 
c) actual opt out (e.g. user clicked some opt-out button)
d) none of the above (no opt out option is given by the website, e.g. no sharing/sale of data on the page or publisher believes they are in a different legal framework)

as for the "illegal": 
yes CA does seem to require the actual opt-out-link but others seem not to need it: e.g. in the gpp CO signals we separate by "SharingNotice", "SaleOptOutNotice" and "SaleOptOut". Hence my assumption is that there is a case when a website only shows a notice but does not offer any opt-out (SharingNotice=1, SaleOptOutNotice=0, SaleOptOut=0)

**Comment by patmmccann** [comment]
The latest proposal is now that we have event listeners in GPP (see #55 ); we can mirror the eventStatus codes from TCF v2 spec. This means that a page can signal with useractioncomplete that an auction is 'ready to go' in say California, even though cmpDisplayStatus may remain 'visible'
