### ISSUE TITLE
Question regarding section encoding - specifically USPCAv1

### ISSUE THREAD

**Issue by yotam-g** [InteractiveAdvertisingBureau/Global-Privacy-Platform#39]
Hello,

For the header encoding, under issue #8, we determined that we would remove any excess padding from the final base64-websafe string and follow these steps: 

1) create the bit representation
2) add padding (0) on the right to a multiple of 6
3) take 6 bits each, starting from the left convert the 6 bits into an integer (e.g. 101010 = 42)
4) convert the integer into a character where the integer is the index of the character in the base64-websafe table (see https://en.wikipedia.org/wiki/Base64; 101010 = 42 = "q")
5) concat the characters to a string

However, I'm not sure how this update affects discrete section encodings. I have not found anything too specific regarding encoding/padding for USPCA under GPP, so should we assume the encoding methodology for both the USPCA core segment & gpc segment will each follow these exact steps after which we would concatenate both segments by a separator "."

Thanks

**Comment by janwinkler** [comment]
You would encode each section separatly using the steps above, convert them into the base64 string and so on and at the end you concat the two segements by "." and then concat the sections with "~" to get the full gpp string.
basically:
[gpp-header]~[(usca-core).(usca-gpc)]
