### ISSUE TITLE
TCF Canada query params and macros

### ISSUE THREAD

**Issue by github-baptiste-haudegand** [InteractiveAdvertisingBureau/Global-Privacy-Platform#43]
Hello !
As TCF Canada is closely following TCF 2.0 EU, especially for the TCString it seems that CMP can collect the consent of the user and forward it to the ad servers without GPP.
But the [TCF EU TCF CA Comparison spec](https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/main/Sections/Canada/TCF%20EU%20TCF%20CA%20Comparison.md) does not provide information related to query parameter names and macros, and it does not provide alternatives to the `gdpr` and `gdpr_consent` query parameters and GDPR macros to receive the information, which is odd, can this be clarified?

**Comment by janwinkler** [comment]
TCF Canada runs via GPP, hence the macros of GPP will be used (${GPP_STRING_XXXXX} ) . same for the parameters.
see here:
https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/main/Core/Consent%20String%20Specification.md#how-does-a-url-based-service-process-the-gpp-string-when-it-cant-execute-javascript
