### ISSUE TITLE
Question about inbound Open RTB fields for GPP

### ISSUE THREAD

**Issue by ym-corey** [InteractiveAdvertisingBureau/Global-Privacy-Platform#50]
Where will the new GPP fields be located?

e.g.,
```
user.ext.gpp
user.ext.gpp_sid
user.ext.gpp_consent
regs.ext.gpp
regs.ext.gpp_sid
regs.ext.gpp_consent
```

If the GPP string contains sections other than what is specified in `gpp_sid`, are they applicable?

Thanks,
Corey

**Comment by janwinkler** [comment]
"GPP assumes the use of OpenRTB 2.x.

    Like other existing privacy signals (TCF and USPrivacy), the GPP string is also able to be transported via OpenRTB. This will be included in the Regs object in the November 2022 release. See this [document](https://github.com/InteractiveAdvertisingBureau/openrtb/tree/master/extensions/community_extensions) for approved design prior to release."

**Comment by ym-corey** [comment]
Hi @janwinkler , I don't see any reference to GPP in that repo, aside from another issue also pointing out that it is missing. https://github.com/InteractiveAdvertisingBureau/openrtb/issues/114.

So we can expect to find either of these fields:

```
regs.gpp
regs.gpp_sid
regs.ext.gpp
regs.ext.gpp_sid
```

**Comment by patmmccann** [comment]
https://github.com/InteractiveAdvertisingBureau/openrtb2.x/blob/main/2.6.md already specifies regs.gpp &
regs.gpp_sid
