### ISSUE TITLE
TCF Canada vs. TCF EU

### ISSUE THREAD

**Issue by miniplanck** [InteractiveAdvertisingBureau/Global-Privacy-Platform#53]
As it stands, the current documentation may be slightly misleading.

While according to [this](https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/main/Sections/Canada/GPPExtension:%20IAB%20Canada%20TCF.md) page some fields such as _IsServiceSpecific_ are not included, in [the comparison](https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/main/Sections/Canada/TCF%20EU%20TCF%20CA%20Comparison.md) is left as **Not Included**, which is distinct.

In practice, the Tcf string is the same, only the Canada format ignores some fields rather than extracting its information.

**Comment by janwinkler** [comment]
Not sure I can follow. In the GPP spec the field is not included for Canada. In the comparison doc it says "📢 Not used in TCF Canada". For me that's both the same. What am I missing?

**Comment by janwinkler** [comment]
PS: TCF String for Canada is not the same (different content + different fields = different string).

**Comment by miniplanck** [comment]
**Detailed explanation:**

Let us assume (**A1**) that, in fact, the TCF Canada String is distinct from a TCF EU String.

According to the [comparision page](https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/main/Sections/Canada/TCF%20EU%20TCF%20CA%20Comparison.md), one example of a Canadian string (**CS**) is 

`CLcVDxRMWfGmWAVAHCENAXCkAKDAADnAABRgA5mdfCKZuYJez-NQm0TBMYA4oCAAGQYIAAAAAAEAIAEgAA.argAC0gAAAAAAAAAAAA`

Now, let us also assume (**A2**) that the fields flagged as "📢 Not used in TCF Canada" are not present the **CS**. This should mean that every field present in this [page](https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/main/Sections/Canada/GPPExtension:%20IAB%20Canada%20TCF.md) ought to be contiguous (**A3**) (according to **A2**). 

Thus, following **A1** and **A2**, one can easily show that the first _MaxVendorId_ is encoded according to _BitField_ encoding, and that its value is 2608. In turns, this implies that the string should have that amount of bits, at least, which is not the case.

So, **A1**, **A2** or **A3** are incorrect. Either the string is the same and  "📢 Not used in TCF Canada" just means that the bits are there but are not read (**A1** and **A2** are broken), or there is something else that is missing.

**Comment by janwinkler** [comment]
I think the first mistake is to use the comparison page as it obviously confuses more than it helps ;-)

Some comments on the issues:
1. The example of the Canadian consent string in the comparison page is not correct. A canadian CS would always be encapsuled in a GPP string. 
2. The comparison page lists the Version as set to "2", while actually TCF Canada is Version "1" (see policy + the GPP section page). Therefore every Canadian consent strings (the section of the GPP string) will always start with a "B" and not a "C"
3. TCF Canada is using fields of types "OptimizedRange" for VendorConsents (and others) while TCF EU is using "OptimizedIntRange". The bit representation can vary a lot depending on the content of the fields. The comparison page is not correct in this case.

**Comment by miniplanck** [comment]
So, if I understand correctly: the comparison ought to be disregarded and only the Canadian one should be paid attention to?
