### ISSUE TITLE
Question about - Sec-GPC in the BidRequest

### ISSUE THREAD

**Issue by sk-vikash** [InteractiveAdvertisingBureau/Global-Privacy-Platform#54]
[This Section ID document](https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/main/Sections/Section%20Information.md#global-privacy-control-gpc) has mentioned about `Sec-GPC`. Can anyone clarify that `Sec-GPC` will be passed in the bid request (based on OpenRTB 2.x) and its encoded in the GPP String? 

Also please share a GPP string example that includes `Sec-GPC` as 1.

**Comment by janwinkler** [comment]
openrtb and gpp are two separate things. a SSP/DSP may decide to send the openrtb field AND the gpp field or only send one (for whatever reason).

**Comment by patmmccann** [comment]
https://github.com/InteractiveAdvertisingBureau/openrtb/pull/99 is relevant
