### ISSUE TITLE
Spec sheet vs. IABGPP site decoder

### ISSUE THREAD

**Issue by miniplanck** [InteractiveAdvertisingBureau/Global-Privacy-Platform#57]
According to the [spec sheet](https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/main/Sections/Canada/GPPExtension:%20IAB%20Canada%20TCF.md), the fields "VendorExpressConsent" and "VendorImpliedConsent" are of OptimizedRange type. 

According to the implementation at [the encoder](https://iabgpp.com/#DBABDA~CPmmxEAPmmxEAPoABABGCyCQAISAAQOAAAAWACADaRIgAg.YAAAAAAAAAA,) the same fields are encoded as type OptimizedIntRange.

Which one is the correct one?

**Comment by janwinkler** [comment]
Please note the difference:
IAB TCF EU will be using Optimized**Int**Range
IAB TCF CA will be using OptimizedRange 

The spec is correct in this case
