### ISSUE TITLE
GPP macro substitution clarification

### ISSUE THREAD

**Issue by infinite-monkeys** [InteractiveAdvertisingBureau/Global-Privacy-Platform#60]
I am reading through the specifications in this repository and am looking for a couple of clarifications as I interpret them.

In the "Consent String Specification" it says:

> GPP_STRING_XXXXX (XXXXX is numeric GPP ID - the ID of the vendor on the GPP ID List who is expecting this URL call)

Why are the GPP string macros tied to the GPP identifier?  It seems like it would be simpler if a caller could use something like `${GPP_STRING}` instead of `${GPP_STRING_XXXXX}`.  Could the GPP string be different for multiple vendors XXXXX in a URL chain? The "CMP API Specification" does not seem to suggest to me that there are vendor-specific GPP strings.

> For macro `${GPP_STRING_XXXXX}`, the service making the call must also check that the macro name contains a valid GPP ID before replacing the macro.

This requirement would require a list of valid vendor IDs to be referenced and checked for validity in code that can just pass these GPP strings through. Would there be an issue if `${GPP_STRING_99999}` were substituted with the GPP string, even if there is no vendor 99999?

From reading these guidelines, it seems like there is some added complication to the macro implementation, but I don't understand the purpose or benefits, and would like to make sure I am not missing something important before working on an implementation.

**Comment by janwinkler** [comment]
The need for a vendor ID comes from the TCF (and potential future frameworks that want to follow the same logic).
The working group agreed to leave the IDs (the "XXXXX") in and will add a wording to the spec describing when and how to use the IDs
