### ISSUE TITLE
Mapping from section number to API prefix

### ISSUE THREAD

**Issue by dgirardi** [InteractiveAdvertisingBureau/Global-Privacy-Platform#72]
I can't find a way to go from section ID to section prefix (or vice-versa) using the CMP API; yet the CMP must have that information.  For example, I can't say "`getSection` for each `applicableSections` ", unless I separately keep a map such as `{"usnat": 7, ...}` to tell which prefix to use.

Is that correct, or did I miss it?

If it is, could/should `getSection` be updated to also accept a section ID as an alternative to the prefix? Or `PingReturn` to include the section ID as part of its `supportedAPIs`?

**Comment by patmmccann** [comment]
maybe we could listen for sectionChange and never call getSection otherwise ?
![image](https://user-images.githubusercontent.com/1683175/234376238-505974fb-49d8-409c-8851-b8198d71a29a.png)

https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/pull/71/files#r1176915477

**Comment by dgirardi** [comment]
That still doesn't provide the association; if I get a `sectionChange` for usnat I can't ask "is usnat applicable?" (unless, again, I separately maintain the same mapping that the CMP has).

**Comment by patmmccann** [comment]
> if I get a sectionChange for usnat I can't ask "is usnat applicable?" 

I don't think you need to, the event has all the data attached.
