### ISSUE TITLE
getField command clarifications in API

### ISSUE THREAD

**Issue by lamrowena** [InteractiveAdvertisingBureau/Global-Privacy-Platform#73]
Additional necessary change needed: getField "parameter" value description and example.

Proposal:
...
parameter - string - API Prefix string + "." (dot) + [Section index* + "." (dot)] + fieldname
return - ..... (stays as it is) ...

The section index is the index of a section within a segment, starting with 0 (zero) for the first section. The section index is optional, if not used, the first section is assumed.

For example, a client can ask the CMP to get the last updated field from the IAB TCF **Canada v1.0** TCData.

var s = __gpp('getField',null, "tcf**ca**.LastUpdated");
or
var s = __gpp('getField',null, "tcfca.0.LastUpdated");

In order to get the Publisher Purposes Express Consent information from IAB TCF Canada the command would be used as:
var s = __gpp('getField',null, "tcfca.1.PubPurposesExpressConsent");

_Originally posted by @janwinkler in https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/issues/71#issuecomment-1516173744_

**Comment by lamrowena** [comment]
@HeinzBaumann "tcfca" is correct based on what we have in [Sections](https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/main/Sections/Section%20Information.md)

**Comment by HeinzBaumann** [comment]
Sorry but this is not correct. The spec calls out in the section API Prefixes: Canada tcfcav1. The API is using that all over the place.

**Comment by lamrowena** [comment]
Ah I see what you are saying. Will need to update the Sections list so that it's consistent.

**Comment by janwinkler** [comment]
So which one is it now? "tcfca" or "tcfcav1"?

**Comment by HeinzBaumann** [comment]
tcfcav1

**Comment by dgirardi** [comment]
There are already CMP implementations that use the names that this thread decided are incorrect (e.g. [consentmanager.net](https://www.consentmanager.net/)), and they are already deployed out in the world ([gppdecoder.com](https://www.gppdecoder.com/)). 

What is the plan for them and their clients? just announce breaking changes in a thread like this, hoping they'll notice? deprecate 1.0 soon?

**Comment by janwinkler** [comment]
@dgirardi There is a long process behind these changes. The process usually ends in a public comment period (e.g. https://iabtechlab.com/blog/public-comment-period-open-for-gpp-api-v1-1/) before a new version gets released.
In this case it is not a normal "breaking change", but the correction of a "bug" in the 1.0 specification (the bug been the use of two different names for the same thing).

**Comment by patmmccann** [comment]
We're using three different names; and implementors have already pointed to tcfca. It is certainly a breaking change to deprecate it. I'd like us to hold 1.1 for the fix.

**Comment by patmmccann** [comment]
Also, what is tcfva https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/87935c4b574e974ff20ff5c1b9641374878031e2/Core/CMP%20API%20Specification.md?plain=1#L900
