### ISSUE TITLE
clarification on MSPA covered transactions

### ISSUE THREAD

**Issue by patmmccann** [InteractiveAdvertisingBureau/Global-Privacy-Platform#74]
We, representing a large number of publishers, recently heard from a large SSP partner that since we are declaring '1' in usnat strings for MspaCoveredTransaction, that they plan to stop sending our bid requests to a large number of non-signatory buyers. This is because they, as a fellow signatory, claim they are obligated not to send requests to non-signatory companies.

As a publisher, it seems we're faced with the following decision:

Continue to pass covered = 1 and lose lots of non-signatory buyers
Pass covered = 2 [not covered] (and consequentially opt out mode = 0) and potentially lose lots of signatory buyers
Abandon GPP until such time as passing the covered flag is not destructive to revenue.  

If these are truly the three options, we're largely forced into scenario three and we imagine all other publishers would be as well. If that's the case, what's the path to adoption? 

Adding further complication, the IAB MSPA implementation guidelines say a transaction can be both covered in the open market and non-covered in deals ([https://www.iabprivacy.com/IAB MSPA Technical Signaling Implementation Guidelines v1.0.pdf](https://www.iabprivacy.com/IAB%20MSPA%20Technical%20Signaling%20Implementation%20Guidelines%20v1.0.pdf)). This suggests the need for a second string or some sort of 'ignore this part of the usnat string' on the pmp object of the ortb2.6 bid request.

And finally, setting non-covered seems to mean you're not allowed to declare you are in 'opt-out option mode', which is another concern, as downstream entities may need to decision on this mode choice.

**Comment by AramZS** [comment]
Worth noting, if this is signatories' general interpretation of the MSPA, [the list is publicly posted](https://tools.iabtechlab.com/mspa) and we can see some major names are missing. No: Magnite, Google, Mediamath,  Trade Desk, Amazon, Unruly, or Rubicon.
