### ISSUE TITLE
API spec and examples have the wrong api name for canada

### ISSUE THREAD

**Issue by patmmccann** [InteractiveAdvertisingBureau/Global-Privacy-Platform#78]
contrast
https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/87935c4b574e974ff20ff5c1b9641374878031e2/Sections/Section%20Information.md?plain=1#L46

with

https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/87935c4b574e974ff20ff5c1b9641374878031e2/Sections/Canada/GPPExtension%3A%20IAB%20Canada%20TCF.md?plain=1#L21

with

https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/87935c4b574e974ff20ff5c1b9641374878031e2/Sections/Canada/GPPExtension%3A%20IAB%20Canada%20TCF.md?plain=1#L20

with

https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/87935c4b574e974ff20ff5c1b9641374878031e2/Core/CMP%20API%20Specification.md?plain=1#L77

with

https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/87935c4b574e974ff20ff5c1b9641374878031e2/Core/CMP%20API%20Specification.md?plain=1#L877

with

https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/87935c4b574e974ff20ff5c1b9641374878031e2/Core/CMP%20API%20Specification.md?plain=1#L1013

**Comment by janwinkler** [comment]
ah yes, duplicate of:
https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/issues/73
