### ISSUE TITLE
I have a question about header example

### ISSUE THREAD

**Issue by mwang-sticky** [InteractiveAdvertisingBureau/Global-Privacy-Platform#8]
@katieshell @lamrowena 
Hoping find you well.
I want to confirm the result for GPP header encoding
In this doc:  https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/main/Core/Consent%20String%20Specification.md
```
Example
Full header bit string: 000011 000001 000000000001 0 011
Encoded header: DBABMA
```
if we use base64-websafe encoding (which the size should be divided by 3 bytes), we need to append the original bit string from 

- from     "0000110000010000000000010011"
- to         "000011000001000000000001001100000000000000000000"
so the result will be DBABMAA
so how can I get "DBABMA" ?

I am looking forward to your help, thanks

**Comment by janwinkler** [comment]
Issue is due to the missing encoding specification (how much padding should be applied). conclusion of one of the last calls was to add padding to 6 bits

**Comment by mwang-sticky** [comment]
I thought base64: when the length of the unencoded input is not a multiple of three, the encoded output must have padding added so that its length is a multiple of four. So should the unencoded input be a multiple of three bytes?

**Comment by janwinkler** [comment]
the decided way to encode is:
1. create the bit representation
2. add padding (0) on the right to a multiple of 6
3. take 6 bits each, starting from the left convert the 6 bits into an integer (e.g. 101010 = 42)
4. convert the integer into a character where the integer is the index of the character in the base64-websafe table (see https://en.wikipedia.org/wiki/Base64; 101010 = 42 = "q")
5. concat the characters to a string

**Comment by bgazzera** [comment]
Thanks for the clarification @janwinkler 
In that case I believe there are some mistakes in the [header examples](https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/main/Core/Consent%20String%20Specification.md):
Header Example 1 : 
```
000011 000001 000000000001 0 011        ==> (groups of 6 bits)
000011 000001 000000 000001 0011        ==> (add padding)
000011 000001 000000 000001 001100      ==> (convert to int)
     3      1      0      1     12      ==> (convert to base64-websafe)
     D      B      A      B      M
```
In the example it is shown as "DBABMA"


Header Example 2
```
000011 000001 000000000010 0 011 0 1011    ==> (groups of 6 bits)
000011 000001 000000 000010 001101 011     ==> (add padding)
000011 000001 000000 000010 001101 011000  ==> (convert to int)
     3      1      0      2     13     24  ==> (convert to base64-websafe)
     D      B      A      C      N      Y
```
In the example it is shown as "DBACNYA"

**Comment by janwinkler** [comment]
yes the example in the docs is not yet updated

**Comment by lamrowena** [comment]
Addressed in https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/pull/83/
