### ISSUE TITLE
Question about Data Type String (fixed length of x)

### ISSUE THREAD

**Issue by shenhui28** [InteractiveAdvertisingBureau/Global-Privacy-Platform#9]
Hi, I have a question about this example under _section encoding_:
<tr>
    <td><code>String (fixed length of x) (including country codes)</code></td>
    <td>x*6 bit</td>
    <td>A fixed amount of bit representing a string. The character’s ASCII integer ID is subtracted by 65 and encoded into an int(6). <br><br>Example: int(6) “101010” represents integer 47 + 65 = char “h”</td>
	  <td></td>
</tr>

"101010" is 42; char "h"'s ASCII integer ID is 104; So how could we get the conclusion:
`Example: int(6) “101010” represents integer 47 + 65 = char “h`

Thanks,

**Comment by janwinkler** [comment]
Yes the example in the spec is incorrect, "101010" = 42+65 = "k"
