### ISSUE TITLE
Wording needs to be updated: Segment vs. Subsection

### ISSUE THREAD

**Issue by janwinkler** [InteractiveAdvertisingBureau/Global-Privacy-Platform#90]
Some places still talk about segments and need to be renamed to subsections. e.g.:
https://github.com/InteractiveAdvertisingBureau/Global-Privacy-Platform/blob/main/Sections/Canada/GPPExtension%3A%20IAB%20Canada%20TCF.md#publisher-purposes-segment

**Comment by lamrowena** [comment]
Will be updated as part of #101
